# redmine_mappings.py

STATUS_OPTIONS = {
    "A fazer": "1",
    "Em andamento": "2",
    "Pronto para homologação": "3",
    "Homologado": "4",
    "Finalizado": "5",
    "Em geração": "7",
    "Aguardando Sprint": "8",
    "Despachar": "9"
}

PRIORITY_OPTIONS = {
    "Baixa": "1",
    "Normal": "2",
    "Alta": "3",
    "Urgente": "4",
    "Imediata": "5"
}

USER_OPTIONS = {
    "Celio Vasconcelos Lima": "8",
    "Igor Alves de Oliveira": "13",
    "Gleice Daiana Vieira de Araujo": "15",
    "Marcus Vinicius Seguti Luis": "16",
    "Welson Elias Rodrigues de Souza": "20",
    "Zeno Dolinski": "89",
    "Winicius Luiz Fidelis de Farias": "91",
    "Luiz Cruz Silveira Neto": "99",
    ".Net GEIN": "129",
    "Pedro Henrique Vieira Silva": "135",
    "ESDRAS FERNANDES FERMON": "137",
    "Lucas Ferreira Madruga": "141",
    "Danilo Ponce": "142",
    "Leandro Gonçalves da Costa": "153",
    "Denise Vieira da Silva Taquary": "156",
    "João Victor Alves Barbosa": "160",
    "Paulo Victor Alves Vieira": "166",
    "Marcos Antônio Campelo Junior": "175",
    "Diogo Bruno Almeida": "6"
}

LOGIN_TO_USER_ID = {
    "danilo.machado": "142",
    "leandro.gcosta": "153"
}

SYSTEM_OPTIONS = {
    "APACHE SPARK": "APACHE SPARK",
    "APLICATIVO DE CONTROLE DE PATRIMÔNIO": "APLICATIVO DE CONTROLE DE PATRIMÔNIO",
    "ATENA": "ATENA",
    "ATLAS": "ATLAS",
    "BLACKLISTWS": "BLACKLISTWS",
    "CADESCO": "CADESCO",
    "COLISEU": "COLISEU",
    "COMANDO DE ENSINO": "COMANDO DE ENSINO",
    "CONDEN": "CONDEN",
    "CONDENWS": "CONDENWS",
    "CONSULTA OBJETOS CIDADÃO": "CONSULTA OBJETOS CIDADÃO",
    "CONTROLE DE LEILÃO": "CONTROLE DE LEILÃO",
    "CONTROLE DE DROGAS": "CONTROLE DE DROGAS",
    "CRONOS": "CRONOS",
    "CSIPM": "CSIPM",
    "DARE": "DARE",
    "DEVOPS": "DEVOPS",
    "DELEGADO VIRTUAL": "DELEGADO VIRTUAL",
    "DENUNCIA 181": "DENUNCIA 181",
    "DREMIO": "DREMIO",
    "ELASTICWS": "ELASTICWS",
    "EMAILWS": "EMAILWS",
    "FILEWS": "FILEWS",
    "FERIAS": "FERIAS",
    "FESACOC": "FESACOC",
    "FUNDO ROTATIVO SGI": "FUNDO ROTATIVO SGI",
    "PROJETOS FLUTTER": "PROJETOS FLUTTER",
    "GDOC": "GDOC",
    "GEOCONTROL": "GEOCONTROL",
    "GOIAS BIOMETRICO": "GOIAS BIOMETRICO",
    "GOIAS BIOMETRICO DESKTOP": "GOIAS BIOMETRICO DESKTOP",
    "GPCD": "GPCD",
    "HADOOP HDFS": "HADOOP HDFS",
    "HPM": "HPM",
    "HIVE": "HIVE",
    "HORUS": "HORUS",
    "I9X SERVICE (GOIAS SEGURO)": "I9X SERVICE (GOIAS SEGURO)",
    "IIVIRTUAL": "IIVIRTUAL",
    "INRC": "INRC",
    "JOBS GEOCONTROL": "JOBS GEOCONTROL",
    "K9": "K9",
    "LEGADOWS": "LEGADOWS",
    "MAPAWS": "MAPAWS",
    "MARIA DA PENHA": "MARIA DA PENHA",
    "MESHPYWS": "MESHPYWS",
    "MINHA CONTA": "MINHA CONTA",
    "MOPI": "MOPI",
    "MPORTAL": "MPORTAL",
    "NIFI": "NIFI",
    "NOVO SICAD": "NOVO SICAD",
    "NOVO SPP": "NOVO SPP",
    "ODIN": "ODIN",
    "PARDAL": "PARDAL",
    "PDFWS": "PDFWS",
    "PORTAL DO CIDADÃO": "PORTAL DO CIDADÃO",
    "PROCON GO": "PROCON GO",
    "PROCON SGC": "PROCON SGC",
    "PROCON VIRTUAL": "PROCON VIRTUAL",
    "PROJUDIWS": "PROJUDIWS",
    "ProProC": "ProProC",
    "PATRULHA RURAL": "PATRULHA RURAL",
    "QLIK SENSE": "QLIK SENSE",
    "RAI ATENDIMENTO": "RAI ATENDIMENTO",
    "RAI DESPACHO": "RAI DESPACHO",
    "RAI DETRAN": "RAI DETRAN",
    "RAI DETRAN ACIDENTE DE TRANSITO": "RAI DETRAN ACIDENTE DE TRANSITO",
    "RAI ESCALA": "RAI ESCALA",
    "RAI RECOMPENSA": "RAI RECOMPENSA",
    "RECORTE ECI PYTHON": "RECORTE ECI PYTHON",
    "RG VIRTUAL COMPARE": "RG VIRTUAL COMPARE",
    "SGI": "SGI",
    "SIAPI": "SIAPI",
    "SICAD": "SICAD",
    "SICOR": "SICOR",
    "SIGA": "SIGA",
    "SIGEP": "SIGEP",
    "SISCPR": "SISCPR",
    "SIGU LEGADO": "SIGU LEGADO",
    "SINALID SERVICE": "SINALID SERVICE",
    "SINESP SERVICE": "SINESP SERVICE",
    "SISPMGO": "SISPMGO",
    "SISOPM": "SISOPM",
    "SISORCRIM": "SISORCRIM",
    "SISP3 SCL": "SISP3 SCL",
    "SISP3 SISP": "SISP3 SISP",
    "SISP3 SPP": "SISP3 SPP",
    "SISPAT": "SISPAT",
    "SISVTR": "SISVTR",
    "SITES": "SITES",
    "SISCOT": "SISCOT",
    "SERVICE DESK GIN": "SERVICE DESK GIN",
    "SSO (SINGLE SIGN-ON)": "SSO (SINGLE SIGN-ON)",
    "TORCEDOR": "TORCEDOR",
    "OUTROS - SOLICITAÇÕES INTERNAS": "OUTROS - SOLICITAÇÕES INTERNAS"
}

ORGAN_OPTIONS = {
    "BM": "BM",
    "CONSEG": "CONSEG",
    "DETRAN": "DETRAN",
    "DGAP": "DGAP",
    "ESPC": "ESPC",
    "GEIT": "GEIT",
    "GGDP": "GGDP",
    "IIGOIÁS": "IIGOIÁS",
    "INTRANET": "INTRANET",
    "INRC": "INRC",
    "OBSERVATÓRIO": "OBSERVATÓRIO",
    "ÓRGÃO EXTERNO": "ÓRGÃO EXTERNO",
    "OUVIDORIA": "OUVIDORIA",
    "PC": "PC",
    "PM": "PM",
    "PP": "PP",
    "PROCON": "PROCON",
    "SEDI": "SEDI",
    "SGI": "SGI",
    "SII": "SII",
    "SPTC": "SPTC",
    "SSP": "SSP",
    "STI": "STI",
    "TJGO": "TJGO"
}

PROJECT_FILTER_OPTIONS = {
    "ATENA": "ATENA",
    "COLISEU": "COLISEU",
    "CONDEN": "CONDEN",
    "CRONOS": "CRONOS",
    "GOIÁS BIOMÉTRICO (DETRAN)": "GOIÁS BIOMÉTRICO (DETRAN)",
    "GOIÁS BIOMÉTRICO (INRC)": "GOIÁS BIOMÉTRICO (INRC)",
    "GOIÁS BIOMÉTRICO (RG NACIONAL)": "GOIÁS BIOMÉTRICO (RG NACIONAL)",
    "GOIÁS BIOMÉTRICO (NEONATAL)": "GOIÁS BIOMÉTRICO (NEONATAL)",
    "GPCD": "GPCD",
    "HORUS": "HORUS",
    "HPM": "HPM",
    "NOVO SPP": "NOVO SPP",
    "NOVO SICAD": "NOVO SICAD",
    "MARIA DA PENHA": "MARIA DA PENHA",
    "MULHER SEGURA": "MULHER SEGURA",
    "PARDAL": "PARDAL",
    "PATRULHA RURAL": "PATRULHA RURAL",
    "PROCON": "PROCON",
    "REFATORAÇÃO SICAD": "REFATORAÇÃO SICAD",
    "SERVICE DESK GIN": "SERVICE DESK GIN",
    "SIAPI 4": "SIAPI 4",
    "SICOR": "SICOR",
    "SIGEP": "SIGEP",
    "SISTEMA DE COMANDO DE ENSINO": "SISTEMA DE COMANDO DE ENSINO",
    "SISTEMA DE FÉRIAS": "SISTEMA DE FÉRIAS",
    "SISTEMA DE GESTÃO ACADÊMICA": "SISTEMA DE GESTÃO ACADÊMICA",
    "TORCEDOR": "TORCEDOR"
}

# redmine_mappings.py

ROLE_OPTIONS = {
    "Analista de Sistemas Pleno": "Analista de Sistemas Pleno",
    "Analista de Sistemas Sênior": "Analista de Sistemas Sênior",
    "Analista de Testes Pleno": "Analista de Testes Pleno",
    "Desenvolvedor Júnior": "Desenvolvedor Júnior",
    "Desenvolvedor Pleno": "Desenvolvedor Pleno",
    "Desenvolvedor Sênior": "Desenvolvedor Sênior",
    "Gerente de Projetos de TIC Sênior": "Gerente de Projetos de TIC Sênior",
    "Analista de Processos Sênior": "Analista de Processos Sênior",
    "Arquiteto de Software Sênior": "Arquiteto de Software Sênior"
}