WITH QUITA_PROCON_POR_PROCESSO AS (
    SELECT
        QPV.ID_NEGOCIACAO_DIVIDA_ATIVA,
        QPV.ID_PROCESSO_DIVIDA_ATIVA,
        MAX(QPV.VALR_TOTAL_COM_DESCONTO) AS VALR_TOTAL_COM_DESCONTO
    FROM SDA.SDA_QUITACAO_PROCON QPV
    GROUP BY
        QPV.ID_NEGOCIACAO_DIVIDA_ATIVA,
        QPV.ID_PROCESSO_DIVIDA_ATIVA
)
SELECT DISTINCT
    PROCESSO.NUMR_PROCESSO_ORGAO AS numeroProcessoOrigem,
    PROCESSO.CODG_DIVISAO AS codigoOrgaoOrigem,
    TRUNC(PARCELA.DATA_QUITACAO_PARCELA) AS dataPagamento,
    QPV.VALR_TOTAL_COM_DESCONTO AS valorPagamentoComDesconto
FROM SDA.SDA_NEGOCIACAO_PROCESSO NEGOCIACAO_PROCESSO
INNER JOIN SDA.SDA_NEGOCIACAO_DIVIDA_ATIVA NEGOCIACAO
    ON NEGOCIACAO_PROCESSO.ID_NEGOCIACAO_DIVIDA_ATIVA = NEGOCIACAO.ID_NEGOCIACAO_DIVIDA_ATIVA
INNER JOIN SDA.SDA_PARCELA_DIVIDA_ATIVA PARCELA
    ON NEGOCIACAO.ID_NEGOCIACAO_DIVIDA_ATIVA = PARCELA.ID_NEGOCIACAO_DIVIDA_ATIVA
INNER JOIN SDA.SDA_DARE_PARCELA DARE
    ON PARCELA.ID_PARCELA_DIVIDA_ATIVA = DARE.ID_PARCELA_DIVIDA_ATIVA
   AND DARE.DATA_PAGAMENTO_DARE IS NOT NULL
INNER JOIN QUITA_PROCON_POR_PROCESSO QPV
    ON QPV.ID_NEGOCIACAO_DIVIDA_ATIVA = NEGOCIACAO.ID_NEGOCIACAO_DIVIDA_ATIVA
   AND QPV.ID_PROCESSO_DIVIDA_ATIVA = NEGOCIACAO_PROCESSO.ID_PROCESSO_DIVIDA_ATIVA
INNER JOIN SDA.SDA_PROCESSO_DIVIDA_ATIVA PROCESSO
    ON PROCESSO.ID_PROCESSO_DIVIDA_ATIVA = NEGOCIACAO_PROCESSO.ID_PROCESSO_DIVIDA_ATIVA
WHERE PARCELA.DATA_QUITACAO_PARCELA IS NOT NULL
  AND DARE.TIPO_DARE = 5
  AND PROCESSO.CODG_DIVISAO = 9666
ORDER BY TRUNC(PARCELA.DATA_QUITACAO_PARCELA);
